ADD Kernel Memory Allocator:
riblanc/kfs pull request #101
Opened 2024-03-06 14:12 UTC by riblanc

2024-03-07 00:36 UTC, riblanc commented
Sorry for da big pull request, whooooops :eyes:

2024-03-08 14:08 UTC, jgiron42 requested changes

2024-03-08 14:08 UTC, jgiron42 commented on src/memory/slab.zig
> +		self.bitmap.set(index, Bit.Free) catch @panic("Slab Allocator: Bitmap corruption detected");
remove panics

2024-03-08 14:10 UTC, riblanc commented on src/memory/fuzzer.zig
> +							printk("invalid checksum, expected {x}, got {x}{x}{x}{x} at {d}\n", .{sum, c, self.allocs[chunk][i+1], self.allocs[chunk][i+2], self.allocs[chunk][i+3], i});
```suggestion
							printk("invalid checksum, expected {x}, got {x} at {d}\n", .{sum, c, i});
```

2024-03-08 15:01 UTC, riblanc commented on src/memory.zig
> +pub var global_cache: @import("memory/cache.zig").GlobalCache = undefined;
Done 577bd61

2024-03-08 15:03 UTC, riblanc commented on src/memory/cache.zig
> +		// Compute the available space for the slab ((page_size * 2^order) - sise of slab header)
Done 9c7f569

2024-03-08 15:40 UTC, riblanc commented on src/memory/slab.zig
> +		self.bitmap.set(index, Bit.Free) catch @panic("Slab Allocator: Bitmap corruption detected");
Done 29f6c71

2024-03-08 15:40 UTC, riblanc commented on src/memory/kernel_memory_allocator.zig
> +		var slab: ?*Slab = if (pfd.next) |slab| @ptrCast(@alignCast(slab)) else null;
Done 29f6c71

2024-03-08 15:42 UTC, riblanc commented on src/memory/cache.zig
> +		) catch @panic("Failed to initialize cache");
Done d92d258

2024-03-08 17:29 UTC, jgiron42 approved these changes

2024-03-08 17:29 UTC, merged